{{- if not .Values.existed_secret_name -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "external-dns.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "external-dns.labels" . | nindent 4 }}
type: Opaque
data:
  "iamkeyfile.json": {{ .Values.config.auth.json | b64enc }}
{{- end }}
